/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppVoterRouteImport } from './routes/_app.voter'
import { Route as AppTradeRouteImport } from './routes/_app.trade'
import { Route as AppToolsRouteImport } from './routes/_app.tools'
import { Route as AppTokensRouteImport } from './routes/_app.tokens'
import { Route as AppSwapRouteImport } from './routes/_app.swap'
import { Route as AppPoolsRouteImport } from './routes/_app.pools'
import { Route as AppP2pRouteImport } from './routes/_app.p2p'
import { Route as AppAnnouncementsRouteImport } from './routes/_app.announcements'
import { Route as AppWalletIndexRouteImport } from './routes/_app.wallet.index'
import { Route as AppToolsIndexRouteImport } from './routes/_app.tools.index'
import { Route as AppP2pIndexRouteImport } from './routes/_app.p2p.index'
import { Route as AppWalletUsernameRouteImport } from './routes/_app.wallet.$username'
import { Route as AppToolsTrailRouteImport } from './routes/_app.tools.trail'
import { Route as AppToolsRewardsRouteImport } from './routes/_app.tools.rewards'
import { Route as AppToolsPromoteRouteImport } from './routes/_app.tools.promote'
import { Route as AppToolsDelegateRouteImport } from './routes/_app.tools.delegate'
import { Route as AppToolsAccountsRouteImport } from './routes/_app.tools.accounts'
import { Route as AppProfileUsernameRouteImport } from './routes/_app.profile.$username'
import { Route as AppPoolPairRouteImport } from './routes/_app.pool.$pair'
import { Route as ApiPublicP2pOffersRouteImport } from './routes/api/public/p2p.offers'
import { Route as AppWalletUsernameTokenRouteImport } from './routes/_app.wallet.$username.$token'
import { Route as AppP2pBuyOfferIdRouteImport } from './routes/_app.p2p.buy.$offerId'
import { Route as ApiPublicP2pReviewsUsernameRouteImport } from './routes/api/public/p2p.reviews.$username'
import { Route as ApiPublicP2pOffersOfferIdRouteImport } from './routes/api/public/p2p.offers.$offerId'
import { Route as ApiPublicP2pActivationUsernameRouteImport } from './routes/api/public/p2p.activation.$username'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVoterRoute = AppVoterRouteImport.update({
  id: '/voter',
  path: '/voter',
  getParentRoute: () => AppRoute,
} as any)
const AppTradeRoute = AppTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsRoute = AppToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AppRoute,
} as any)
const AppTokensRoute = AppTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AppRoute,
} as any)
const AppSwapRoute = AppSwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => AppRoute,
} as any)
const AppPoolsRoute = AppPoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => AppRoute,
} as any)
const AppP2pRoute = AppP2pRouteImport.update({
  id: '/p2p',
  path: '/p2p',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletIndexRoute = AppWalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsIndexRoute = AppToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppToolsRoute,
} as any)
const AppP2pIndexRoute = AppP2pIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppP2pRoute,
} as any)
const AppWalletUsernameRoute = AppWalletUsernameRouteImport.update({
  id: '/wallet/$username',
  path: '/wallet/$username',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsTrailRoute = AppToolsTrailRouteImport.update({
  id: '/trail',
  path: '/trail',
  getParentRoute: () => AppToolsRoute,
} as any)
const AppToolsRewardsRoute = AppToolsRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AppToolsRoute,
} as any)
const AppToolsPromoteRoute = AppToolsPromoteRouteImport.update({
  id: '/promote',
  path: '/promote',
  getParentRoute: () => AppToolsRoute,
} as any)
const AppToolsDelegateRoute = AppToolsDelegateRouteImport.update({
  id: '/delegate',
  path: '/delegate',
  getParentRoute: () => AppToolsRoute,
} as any)
const AppToolsAccountsRoute = AppToolsAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppToolsRoute,
} as any)
const AppProfileUsernameRoute = AppProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => AppRoute,
} as any)
const AppPoolPairRoute = AppPoolPairRouteImport.update({
  id: '/pool/$pair',
  path: '/pool/$pair',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicP2pOffersRoute = ApiPublicP2pOffersRouteImport.update({
  id: '/api/public/p2p/offers',
  path: '/api/public/p2p/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletUsernameTokenRoute = AppWalletUsernameTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => AppWalletUsernameRoute,
} as any)
const AppP2pBuyOfferIdRoute = AppP2pBuyOfferIdRouteImport.update({
  id: '/buy/$offerId',
  path: '/buy/$offerId',
  getParentRoute: () => AppP2pRoute,
} as any)
const ApiPublicP2pReviewsUsernameRoute =
  ApiPublicP2pReviewsUsernameRouteImport.update({
    id: '/api/public/p2p/reviews/$username',
    path: '/api/public/p2p/reviews/$username',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicP2pOffersOfferIdRoute =
  ApiPublicP2pOffersOfferIdRouteImport.update({
    id: '/$offerId',
    path: '/$offerId',
    getParentRoute: () => ApiPublicP2pOffersRoute,
  } as any)
const ApiPublicP2pActivationUsernameRoute =
  ApiPublicP2pActivationUsernameRouteImport.update({
    id: '/api/public/p2p/activation/$username',
    path: '/api/public/p2p/activation/$username',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/p2p': typeof AppP2pRouteWithChildren
  '/pools': typeof AppPoolsRoute
  '/swap': typeof AppSwapRoute
  '/tokens': typeof AppTokensRoute
  '/tools': typeof AppToolsRouteWithChildren
  '/trade': typeof AppTradeRoute
  '/voter': typeof AppVoterRoute
  '/pool/$pair': typeof AppPoolPairRoute
  '/profile/$username': typeof AppProfileUsernameRoute
  '/tools/accounts': typeof AppToolsAccountsRoute
  '/tools/delegate': typeof AppToolsDelegateRoute
  '/tools/promote': typeof AppToolsPromoteRoute
  '/tools/rewards': typeof AppToolsRewardsRoute
  '/tools/trail': typeof AppToolsTrailRoute
  '/wallet/$username': typeof AppWalletUsernameRouteWithChildren
  '/p2p/': typeof AppP2pIndexRoute
  '/tools/': typeof AppToolsIndexRoute
  '/wallet/': typeof AppWalletIndexRoute
  '/p2p/buy/$offerId': typeof AppP2pBuyOfferIdRoute
  '/wallet/$username/$token': typeof AppWalletUsernameTokenRoute
  '/api/public/p2p/offers': typeof ApiPublicP2pOffersRouteWithChildren
  '/api/public/p2p/activation/$username': typeof ApiPublicP2pActivationUsernameRoute
  '/api/public/p2p/offers/$offerId': typeof ApiPublicP2pOffersOfferIdRoute
  '/api/public/p2p/reviews/$username': typeof ApiPublicP2pReviewsUsernameRoute
}
export interface FileRoutesByTo {
  '/announcements': typeof AppAnnouncementsRoute
  '/pools': typeof AppPoolsRoute
  '/swap': typeof AppSwapRoute
  '/tokens': typeof AppTokensRoute
  '/trade': typeof AppTradeRoute
  '/voter': typeof AppVoterRoute
  '/': typeof AppIndexRoute
  '/pool/$pair': typeof AppPoolPairRoute
  '/profile/$username': typeof AppProfileUsernameRoute
  '/tools/accounts': typeof AppToolsAccountsRoute
  '/tools/delegate': typeof AppToolsDelegateRoute
  '/tools/promote': typeof AppToolsPromoteRoute
  '/tools/rewards': typeof AppToolsRewardsRoute
  '/tools/trail': typeof AppToolsTrailRoute
  '/wallet/$username': typeof AppWalletUsernameRouteWithChildren
  '/p2p': typeof AppP2pIndexRoute
  '/tools': typeof AppToolsIndexRoute
  '/wallet': typeof AppWalletIndexRoute
  '/p2p/buy/$offerId': typeof AppP2pBuyOfferIdRoute
  '/wallet/$username/$token': typeof AppWalletUsernameTokenRoute
  '/api/public/p2p/offers': typeof ApiPublicP2pOffersRouteWithChildren
  '/api/public/p2p/activation/$username': typeof ApiPublicP2pActivationUsernameRoute
  '/api/public/p2p/offers/$offerId': typeof ApiPublicP2pOffersOfferIdRoute
  '/api/public/p2p/reviews/$username': typeof ApiPublicP2pReviewsUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/announcements': typeof AppAnnouncementsRoute
  '/_app/p2p': typeof AppP2pRouteWithChildren
  '/_app/pools': typeof AppPoolsRoute
  '/_app/swap': typeof AppSwapRoute
  '/_app/tokens': typeof AppTokensRoute
  '/_app/tools': typeof AppToolsRouteWithChildren
  '/_app/trade': typeof AppTradeRoute
  '/_app/voter': typeof AppVoterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/pool/$pair': typeof AppPoolPairRoute
  '/_app/profile/$username': typeof AppProfileUsernameRoute
  '/_app/tools/accounts': typeof AppToolsAccountsRoute
  '/_app/tools/delegate': typeof AppToolsDelegateRoute
  '/_app/tools/promote': typeof AppToolsPromoteRoute
  '/_app/tools/rewards': typeof AppToolsRewardsRoute
  '/_app/tools/trail': typeof AppToolsTrailRoute
  '/_app/wallet/$username': typeof AppWalletUsernameRouteWithChildren
  '/_app/p2p/': typeof AppP2pIndexRoute
  '/_app/tools/': typeof AppToolsIndexRoute
  '/_app/wallet/': typeof AppWalletIndexRoute
  '/_app/p2p/buy/$offerId': typeof AppP2pBuyOfferIdRoute
  '/_app/wallet/$username/$token': typeof AppWalletUsernameTokenRoute
  '/api/public/p2p/offers': typeof ApiPublicP2pOffersRouteWithChildren
  '/api/public/p2p/activation/$username': typeof ApiPublicP2pActivationUsernameRoute
  '/api/public/p2p/offers/$offerId': typeof ApiPublicP2pOffersOfferIdRoute
  '/api/public/p2p/reviews/$username': typeof ApiPublicP2pReviewsUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/p2p'
    | '/pools'
    | '/swap'
    | '/tokens'
    | '/tools'
    | '/trade'
    | '/voter'
    | '/pool/$pair'
    | '/profile/$username'
    | '/tools/accounts'
    | '/tools/delegate'
    | '/tools/promote'
    | '/tools/rewards'
    | '/tools/trail'
    | '/wallet/$username'
    | '/p2p/'
    | '/tools/'
    | '/wallet/'
    | '/p2p/buy/$offerId'
    | '/wallet/$username/$token'
    | '/api/public/p2p/offers'
    | '/api/public/p2p/activation/$username'
    | '/api/public/p2p/offers/$offerId'
    | '/api/public/p2p/reviews/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/announcements'
    | '/pools'
    | '/swap'
    | '/tokens'
    | '/trade'
    | '/voter'
    | '/'
    | '/pool/$pair'
    | '/profile/$username'
    | '/tools/accounts'
    | '/tools/delegate'
    | '/tools/promote'
    | '/tools/rewards'
    | '/tools/trail'
    | '/wallet/$username'
    | '/p2p'
    | '/tools'
    | '/wallet'
    | '/p2p/buy/$offerId'
    | '/wallet/$username/$token'
    | '/api/public/p2p/offers'
    | '/api/public/p2p/activation/$username'
    | '/api/public/p2p/offers/$offerId'
    | '/api/public/p2p/reviews/$username'
  id:
    | '__root__'
    | '/_app'
    | '/_app/announcements'
    | '/_app/p2p'
    | '/_app/pools'
    | '/_app/swap'
    | '/_app/tokens'
    | '/_app/tools'
    | '/_app/trade'
    | '/_app/voter'
    | '/_app/'
    | '/_app/pool/$pair'
    | '/_app/profile/$username'
    | '/_app/tools/accounts'
    | '/_app/tools/delegate'
    | '/_app/tools/promote'
    | '/_app/tools/rewards'
    | '/_app/tools/trail'
    | '/_app/wallet/$username'
    | '/_app/p2p/'
    | '/_app/tools/'
    | '/_app/wallet/'
    | '/_app/p2p/buy/$offerId'
    | '/_app/wallet/$username/$token'
    | '/api/public/p2p/offers'
    | '/api/public/p2p/activation/$username'
    | '/api/public/p2p/offers/$offerId'
    | '/api/public/p2p/reviews/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiPublicP2pOffersRoute: typeof ApiPublicP2pOffersRouteWithChildren
  ApiPublicP2pActivationUsernameRoute: typeof ApiPublicP2pActivationUsernameRoute
  ApiPublicP2pReviewsUsernameRoute: typeof ApiPublicP2pReviewsUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voter': {
      id: '/_app/voter'
      path: '/voter'
      fullPath: '/voter'
      preLoaderRoute: typeof AppVoterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trade': {
      id: '/_app/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof AppTradeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools': {
      id: '/_app/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AppToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tokens': {
      id: '/_app/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof AppTokensRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/swap': {
      id: '/_app/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof AppSwapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pools': {
      id: '/_app/pools'
      path: '/pools'
      fullPath: '/pools'
      preLoaderRoute: typeof AppPoolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/p2p': {
      id: '/_app/p2p'
      path: '/p2p'
      fullPath: '/p2p'
      preLoaderRoute: typeof AppP2pRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/announcements': {
      id: '/_app/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wallet/': {
      id: '/_app/wallet/'
      path: '/wallet'
      fullPath: '/wallet/'
      preLoaderRoute: typeof AppWalletIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/': {
      id: '/_app/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof AppToolsIndexRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/_app/p2p/': {
      id: '/_app/p2p/'
      path: '/'
      fullPath: '/p2p/'
      preLoaderRoute: typeof AppP2pIndexRouteImport
      parentRoute: typeof AppP2pRoute
    }
    '/_app/wallet/$username': {
      id: '/_app/wallet/$username'
      path: '/wallet/$username'
      fullPath: '/wallet/$username'
      preLoaderRoute: typeof AppWalletUsernameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/trail': {
      id: '/_app/tools/trail'
      path: '/trail'
      fullPath: '/tools/trail'
      preLoaderRoute: typeof AppToolsTrailRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/_app/tools/rewards': {
      id: '/_app/tools/rewards'
      path: '/rewards'
      fullPath: '/tools/rewards'
      preLoaderRoute: typeof AppToolsRewardsRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/_app/tools/promote': {
      id: '/_app/tools/promote'
      path: '/promote'
      fullPath: '/tools/promote'
      preLoaderRoute: typeof AppToolsPromoteRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/_app/tools/delegate': {
      id: '/_app/tools/delegate'
      path: '/delegate'
      fullPath: '/tools/delegate'
      preLoaderRoute: typeof AppToolsDelegateRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/_app/tools/accounts': {
      id: '/_app/tools/accounts'
      path: '/accounts'
      fullPath: '/tools/accounts'
      preLoaderRoute: typeof AppToolsAccountsRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/_app/profile/$username': {
      id: '/_app/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AppProfileUsernameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pool/$pair': {
      id: '/_app/pool/$pair'
      path: '/pool/$pair'
      fullPath: '/pool/$pair'
      preLoaderRoute: typeof AppPoolPairRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/p2p/offers': {
      id: '/api/public/p2p/offers'
      path: '/api/public/p2p/offers'
      fullPath: '/api/public/p2p/offers'
      preLoaderRoute: typeof ApiPublicP2pOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wallet/$username/$token': {
      id: '/_app/wallet/$username/$token'
      path: '/$token'
      fullPath: '/wallet/$username/$token'
      preLoaderRoute: typeof AppWalletUsernameTokenRouteImport
      parentRoute: typeof AppWalletUsernameRoute
    }
    '/_app/p2p/buy/$offerId': {
      id: '/_app/p2p/buy/$offerId'
      path: '/buy/$offerId'
      fullPath: '/p2p/buy/$offerId'
      preLoaderRoute: typeof AppP2pBuyOfferIdRouteImport
      parentRoute: typeof AppP2pRoute
    }
    '/api/public/p2p/reviews/$username': {
      id: '/api/public/p2p/reviews/$username'
      path: '/api/public/p2p/reviews/$username'
      fullPath: '/api/public/p2p/reviews/$username'
      preLoaderRoute: typeof ApiPublicP2pReviewsUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/p2p/offers/$offerId': {
      id: '/api/public/p2p/offers/$offerId'
      path: '/$offerId'
      fullPath: '/api/public/p2p/offers/$offerId'
      preLoaderRoute: typeof ApiPublicP2pOffersOfferIdRouteImport
      parentRoute: typeof ApiPublicP2pOffersRoute
    }
    '/api/public/p2p/activation/$username': {
      id: '/api/public/p2p/activation/$username'
      path: '/api/public/p2p/activation/$username'
      fullPath: '/api/public/p2p/activation/$username'
      preLoaderRoute: typeof ApiPublicP2pActivationUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppP2pRouteChildren {
  AppP2pIndexRoute: typeof AppP2pIndexRoute
  AppP2pBuyOfferIdRoute: typeof AppP2pBuyOfferIdRoute
}

const AppP2pRouteChildren: AppP2pRouteChildren = {
  AppP2pIndexRoute: AppP2pIndexRoute,
  AppP2pBuyOfferIdRoute: AppP2pBuyOfferIdRoute,
}

const AppP2pRouteWithChildren =
  AppP2pRoute._addFileChildren(AppP2pRouteChildren)

interface AppToolsRouteChildren {
  AppToolsAccountsRoute: typeof AppToolsAccountsRoute
  AppToolsDelegateRoute: typeof AppToolsDelegateRoute
  AppToolsPromoteRoute: typeof AppToolsPromoteRoute
  AppToolsRewardsRoute: typeof AppToolsRewardsRoute
  AppToolsTrailRoute: typeof AppToolsTrailRoute
  AppToolsIndexRoute: typeof AppToolsIndexRoute
}

const AppToolsRouteChildren: AppToolsRouteChildren = {
  AppToolsAccountsRoute: AppToolsAccountsRoute,
  AppToolsDelegateRoute: AppToolsDelegateRoute,
  AppToolsPromoteRoute: AppToolsPromoteRoute,
  AppToolsRewardsRoute: AppToolsRewardsRoute,
  AppToolsTrailRoute: AppToolsTrailRoute,
  AppToolsIndexRoute: AppToolsIndexRoute,
}

const AppToolsRouteWithChildren = AppToolsRoute._addFileChildren(
  AppToolsRouteChildren,
)

interface AppWalletUsernameRouteChildren {
  AppWalletUsernameTokenRoute: typeof AppWalletUsernameTokenRoute
}

const AppWalletUsernameRouteChildren: AppWalletUsernameRouteChildren = {
  AppWalletUsernameTokenRoute: AppWalletUsernameTokenRoute,
}

const AppWalletUsernameRouteWithChildren =
  AppWalletUsernameRoute._addFileChildren(AppWalletUsernameRouteChildren)

interface AppRouteChildren {
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppP2pRoute: typeof AppP2pRouteWithChildren
  AppPoolsRoute: typeof AppPoolsRoute
  AppSwapRoute: typeof AppSwapRoute
  AppTokensRoute: typeof AppTokensRoute
  AppToolsRoute: typeof AppToolsRouteWithChildren
  AppTradeRoute: typeof AppTradeRoute
  AppVoterRoute: typeof AppVoterRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPoolPairRoute: typeof AppPoolPairRoute
  AppProfileUsernameRoute: typeof AppProfileUsernameRoute
  AppWalletUsernameRoute: typeof AppWalletUsernameRouteWithChildren
  AppWalletIndexRoute: typeof AppWalletIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppP2pRoute: AppP2pRouteWithChildren,
  AppPoolsRoute: AppPoolsRoute,
  AppSwapRoute: AppSwapRoute,
  AppTokensRoute: AppTokensRoute,
  AppToolsRoute: AppToolsRouteWithChildren,
  AppTradeRoute: AppTradeRoute,
  AppVoterRoute: AppVoterRoute,
  AppIndexRoute: AppIndexRoute,
  AppPoolPairRoute: AppPoolPairRoute,
  AppProfileUsernameRoute: AppProfileUsernameRoute,
  AppWalletUsernameRoute: AppWalletUsernameRouteWithChildren,
  AppWalletIndexRoute: AppWalletIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiPublicP2pOffersRouteChildren {
  ApiPublicP2pOffersOfferIdRoute: typeof ApiPublicP2pOffersOfferIdRoute
}

const ApiPublicP2pOffersRouteChildren: ApiPublicP2pOffersRouteChildren = {
  ApiPublicP2pOffersOfferIdRoute: ApiPublicP2pOffersOfferIdRoute,
}

const ApiPublicP2pOffersRouteWithChildren =
  ApiPublicP2pOffersRoute._addFileChildren(ApiPublicP2pOffersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiPublicP2pOffersRoute: ApiPublicP2pOffersRouteWithChildren,
  ApiPublicP2pActivationUsernameRoute: ApiPublicP2pActivationUsernameRoute,
  ApiPublicP2pReviewsUsernameRoute: ApiPublicP2pReviewsUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
