// lib/modules/game-stats/model.server.ts
import mongoose, { Schema, type Model } from "mongoose";
import type { IGameStat } from "./types.server";

/**
 * One document per stat key in the "game-stats" collection.
 * Counters use $inc (atomic). Snapshots use $set via setStat().
 *
 * Counter keys:
 *   itemNumber          — global item serial (monotonically increasing)
 *   registeredPlayers   — total accounts ever created
 *   totalChestsOpened   — all chests opened across all players
 *   totalRaids          — all raid attempts game-wide
 *   totalRaidWins       — all successful raids game-wide
 *   totalHashMined      — cumulative HASH generated by all players
 *   totalHashBurned     — cumulative HASH destroyed via upgrades/fees
 *   totalHashClaimed    — cumulative HASH moved to liquid wallets
 *   totalHashDeposited  — cumulative on-chain SPL deposits credited in-game
 *   totalHashWithdrawn  — cumulative in-game HASH paid out on-chain
 *   totalMarketSales    — all marketplace purchases settled by the worker
 *
 * Snapshot keys (overwritten, not incremented):
 *   activePlayers24h    — players who ticked in the last 24h
 *   hashInCirculation   — sum of all player `hash` balances
 *   hashInVaults        — sum of all player `vault` values
 */
const GameStatSchema = new Schema<IGameStat>(
  {
    _id: { type: String },
    value: { type: Number, default: 0 },
    updatedAt: { type: Number, default: () => Date.now() },
  },
  { collection: "game-stats", _id: false },
);

export const GameStatModel: Model<IGameStat> =
  mongoose.models["GameStat"] ?? mongoose.model<IGameStat>("GameStat", GameStatSchema);
